#! /usr/bin/env sh
# -*- Shell-script -*-
# $Id: gen,v 1.1 2002-06-15 02:27:51 npsimons Exp $
# Copyright (C) 2002, Nathan Paul Simons <npsimons@hardcorehackers.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or 
# (at your option) any later version.
#   
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
# GNU General Public License for more details.
#   
# You should have received a copy of the GNU General Public License 
# along with this program; if not, write to the Free Software 
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA. 
#
# Alternatively, the GPL can be found at 
# http://www.gnu.org/copyleft/gpl.html
#
# Generate files from automake/autoconf and associated utils.
# Only run this if you are a developer/know what you are doing.

set -e
#cvs update -d -P -R
aclocal --verbose
automake --add-missing --copy --verbose
autoheader
autoconf
#./configure --prefix=/usr/local
#make

